#!/bin/bash

vm_name="master"
ip_output_name=$vm_name"_public_ip"
public_ip=$(terraform output --raw $ip_output_name)
key_name=$vm_name".pem"


# setup ssh key
terraform output --raw ssh_private_key > $key_name
chmod 600 $key_name

# ssh into instance
mkdir -p ~/.kube
scp -i $key_name $(terraform output --raw root_user)@$public_ip:/etc/rancher/k3s/k3s.yaml ~/.kube/config.temp.yaml
cat ~/.kube/config.temp.yaml | sed "s/127.0.0.1/$public_ip/g" > ~/.kube/config
rm ~/.kube/config.temp.yaml

# remove ssh key
rm $key_name