#!/bin/bash

vm_name=$1
output_name=$vm_name"_public_ip"
key_name=$vm_name".pem"

# setup ssh key
terraform output --raw ssh_private_key > $key_name
chmod 600 $key_name

# ssh into instance
ssh -i $key_name $(terraform output --raw root_user)@$(terraform output --raw $output_name)

# remove ssh key
rm $key_name