- hosts: all
  become: yes
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: "Install wireguard"
      apt:
        name: "wireguard"
        state: present
